apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows11-disk
  namespace: retail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  storageClassName: local-path
